version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cost_warehouse
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cost_analytics
    ports:
      - "5432:5432"

